# Generated by Django 5.1.4 on 2025-02-25 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_TrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da Categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_img/categories')),
                ('path', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Caminho da Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do departamento')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_img/departments')),
                ('path', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Caminho da Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do fornecedor')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_img/suppliers')),
                ('path', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Caminho da Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rfid_tag', models.CharField(max_length=50, unique=True, verbose_name='Tag RFID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Ativo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Ativo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_img/assets')),
                ('path', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Caminho da Imagem')),
                ('availability', models.BooleanField(default=False, verbose_name='Disponibilidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets_TrackerApp.categories', verbose_name='Categoria')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets_TrackerApp.departments', verbose_name='Departamento')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets_TrackerApp.suppliers', verbose_name='Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Movimentação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='assets_TrackerApp.assets', verbose_name='Ativo')),
                ('destination_dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_destination', to='assets_TrackerApp.departments', verbose_name='Departamento de Destino')),
                ('origin_dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_origin', to='assets_TrackerApp.departments', verbose_name='Departamento de Origem')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_TrackerApp.user', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-movement_date'],
            },
        ),
    ]
